import { JSONSchema7 } from "json-schema";
import { OpenBrowserDialogue } from "../dialogue";
import Context from "../context";
import { sub } from "../../common/utils";
import { TOOL_NAME as task_planner } from "./task_planner";
import { DialogueTool, OpenBrowserResult, ToolResult } from "../../types";

export const TOOL_NAME = "executeTask";

export default class ExecuteTaskTool implements DialogueTool {
  readonly name: string = TOOL_NAME;
  readonly description: string;
  readonly parameters: JSONSchema7;
  private openbrowserDialogue: OpenBrowserDialogue;

  constructor(openbrowserDialogue: OpenBrowserDialogue) {
    this.description = `Responsible for executing the task plan generated by the ${task_planner}. Use this tool if you need to execute planned tasks.`;
    this.parameters = {
      type: "object",
      properties: {
        taskId: {
          type: "string",
          description: `Task ID, generated by the \`${task_planner}\` tool.`
        }
      },
      required: ["taskId"]
    };
    this.openbrowserDialogue = openbrowserDialogue;
  }

  async execute(args: Record<string, unknown>): Promise<ToolResult> {
    const taskId = args.taskId as string;
    const openbrowser = this.openbrowserDialogue.getOpenBrowser(taskId);
    if (!openbrowser) {
      return {
        content: [
          {
            type: "text",
            text: "Error: Task ID not found."
          }
        ]
      };
    }
    const result = await openbrowser.execute(taskId);
    const context = openbrowser.getTask(taskId);
    const variables = context?.variables;
    if (variables) {
      for (const key of variables.keys()) {
        this.openbrowserDialogue
          .getGlobalContext()
          .set(key, variables.get(key));
      }
    }
    if (context) {
      return this.getTaskResult(context, result);
    } else {
      return {
        content: [
          {
            type: "text",
            text: result.result
          }
        ]
      };
    }
  }

  private getTaskResult(
    context: Context,
    openbrowserResult: OpenBrowserResult
  ): ToolResult {
    let result =
      "# Task execution result\n" + JSON.stringify(openbrowserResult, null, 2);
    if (context.chain.agents.length > 1) {
      result += "\n\n## Subtask execution results";
      for (let i = 0; i < context.chain.agents.length; i++) {
        let agentChain = context.chain.agents[i];
        if (agentChain.agentResult) {
          const task = agentChain.agent.task || agentChain.agent.name;
          result += `\n### ${task}\n${sub(agentChain.agentResult, 800, true)}`;
        }
      }
    }
    return {
      content: [
        {
          type: "text",
          text: result
        }
      ]
    };
  }
}

export { ExecuteTaskTool as DeepActionTool };
